// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tokenizer/v1/tokenizer.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountTokensRequest) Reset() {
	*x = CountTokensRequest{}
	mi := &file_tokenizer_v1_tokenizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountTokensRequest) ProtoMessage() {}

func (x *CountTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tokenizer_v1_tokenizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountTokensRequest.ProtoReflect.Descriptor instead.
func (*CountTokensRequest) Descriptor() ([]byte, []int) {
	return file_tokenizer_v1_tokenizer_proto_rawDescGZIP(), []int{0}
}

func (x *CountTokensRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CountTokensRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CountTokensRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type CountTokensResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TokenCount          int32                  `protobuf:"varint,1,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	ExceedsBudget       bool                   `protobuf:"varint,2,opt,name=exceeds_budget,json=exceedsBudget,proto3" json:"exceeds_budget,omitempty"`
	SuggestedTruncation int32                  `protobuf:"varint,3,opt,name=suggested_truncation,json=suggestedTruncation,proto3" json:"suggested_truncation,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CountTokensResponse) Reset() {
	*x = CountTokensResponse{}
	mi := &file_tokenizer_v1_tokenizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountTokensResponse) ProtoMessage() {}

func (x *CountTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tokenizer_v1_tokenizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountTokensResponse.ProtoReflect.Descriptor instead.
func (*CountTokensResponse) Descriptor() ([]byte, []int) {
	return file_tokenizer_v1_tokenizer_proto_rawDescGZIP(), []int{1}
}

func (x *CountTokensResponse) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *CountTokensResponse) GetExceedsBudget() bool {
	if x != nil {
		return x.ExceedsBudget
	}
	return false
}

func (x *CountTokensResponse) GetSuggestedTruncation() int32 {
	if x != nil {
		return x.SuggestedTruncation
	}
	return 0
}

var File_tokenizer_v1_tokenizer_proto protoreflect.FileDescriptor

const file_tokenizer_v1_tokenizer_proto_rawDesc = "" +
	"\n" +
	"\x1ctokenizer/v1/tokenizer.proto\x12\ftokenizer.v1\"a\n" +
	"\x12CountTokensRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\"\x90\x01\n" +
	"\x13CountTokensResponse\x12\x1f\n" +
	"\vtoken_count\x18\x01 \x01(\x05R\n" +
	"tokenCount\x12%\n" +
	"\x0eexceeds_budget\x18\x02 \x01(\bR\rexceedsBudget\x121\n" +
	"\x14suggested_truncation\x18\x03 \x01(\x05R\x13suggestedTruncation2f\n" +
	"\x10TokenizerService\x12R\n" +
	"\vCountTokens\x12 .tokenizer.v1.CountTokensRequest\x1a!.tokenizer.v1.CountTokensResponseB@Z>github.com/fadyphil/llm-batching-gateway/proto/go/tokenizer/v1b\x06proto3"

var (
	file_tokenizer_v1_tokenizer_proto_rawDescOnce sync.Once
	file_tokenizer_v1_tokenizer_proto_rawDescData []byte
)

func file_tokenizer_v1_tokenizer_proto_rawDescGZIP() []byte {
	file_tokenizer_v1_tokenizer_proto_rawDescOnce.Do(func() {
		file_tokenizer_v1_tokenizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tokenizer_v1_tokenizer_proto_rawDesc), len(file_tokenizer_v1_tokenizer_proto_rawDesc)))
	})
	return file_tokenizer_v1_tokenizer_proto_rawDescData
}

var file_tokenizer_v1_tokenizer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tokenizer_v1_tokenizer_proto_goTypes = []any{
	(*CountTokensRequest)(nil),  // 0: tokenizer.v1.CountTokensRequest
	(*CountTokensResponse)(nil), // 1: tokenizer.v1.CountTokensResponse
}
var file_tokenizer_v1_tokenizer_proto_depIdxs = []int32{
	0, // 0: tokenizer.v1.TokenizerService.CountTokens:input_type -> tokenizer.v1.CountTokensRequest
	1, // 1: tokenizer.v1.TokenizerService.CountTokens:output_type -> tokenizer.v1.CountTokensResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tokenizer_v1_tokenizer_proto_init() }
func file_tokenizer_v1_tokenizer_proto_init() {
	if File_tokenizer_v1_tokenizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tokenizer_v1_tokenizer_proto_rawDesc), len(file_tokenizer_v1_tokenizer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tokenizer_v1_tokenizer_proto_goTypes,
		DependencyIndexes: file_tokenizer_v1_tokenizer_proto_depIdxs,
		MessageInfos:      file_tokenizer_v1_tokenizer_proto_msgTypes,
	}.Build()
	File_tokenizer_v1_tokenizer_proto = out.File
	file_tokenizer_v1_tokenizer_proto_goTypes = nil
	file_tokenizer_v1_tokenizer_proto_depIdxs = nil
}
