// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: scheduler/v1/scheduler.proto

package v1

import (
	v1 "github.com/fadyphil/llm-batching-gateway/proto/go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnqueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Priority      v1.Priority            `protobuf:"varint,5,opt,name=priority,proto3,enum=common.v1.Priority" json:"priority,omitempty"`
	TokenCount    int32                  `protobuf:"varint,6,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EnqueueRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EnqueueRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *EnqueueRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EnqueueRequest) GetPriority() v1.Priority {
	if x != nil {
		return x.Priority
	}
	return v1.Priority(0)
}

func (x *EnqueueRequest) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	IsFinal       bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	FinishReason  string                 `protobuf:"bytes,4,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EnqueueResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnqueueResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *EnqueueResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

var File_scheduler_v1_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_v1_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x1cscheduler/v1/scheduler.proto\x12\fscheduler.v1\x1a\x16common/v1/common.proto\"\xce\x01\n" +
	"\x0eEnqueueRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12/\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x13.common.v1.PriorityR\bpriority\x12\x1f\n" +
	"\vtoken_count\x18\x06 \x01(\x05R\n" +
	"tokenCount\"\x86\x01\n" +
	"\x0fEnqueueResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\x12#\n" +
	"\rfinish_reason\x18\x04 \x01(\tR\ffinishReason2\\\n" +
	"\x10SchedulerService\x12H\n" +
	"\aEnqueue\x12\x1c.scheduler.v1.EnqueueRequest\x1a\x1d.scheduler.v1.EnqueueResponse0\x01B@Z>github.com/fadyphil/llm-batching-gateway/proto/go/scheduler/v1b\x06proto3"

var (
	file_scheduler_v1_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_v1_scheduler_proto_rawDescData []byte
)

func file_scheduler_v1_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_v1_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_v1_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_v1_scheduler_proto_rawDesc), len(file_scheduler_v1_scheduler_proto_rawDesc)))
	})
	return file_scheduler_v1_scheduler_proto_rawDescData
}

var file_scheduler_v1_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scheduler_v1_scheduler_proto_goTypes = []any{
	(*EnqueueRequest)(nil),  // 0: scheduler.v1.EnqueueRequest
	(*EnqueueResponse)(nil), // 1: scheduler.v1.EnqueueResponse
	(v1.Priority)(0),        // 2: common.v1.Priority
}
var file_scheduler_v1_scheduler_proto_depIdxs = []int32{
	2, // 0: scheduler.v1.EnqueueRequest.priority:type_name -> common.v1.Priority
	0, // 1: scheduler.v1.SchedulerService.Enqueue:input_type -> scheduler.v1.EnqueueRequest
	1, // 2: scheduler.v1.SchedulerService.Enqueue:output_type -> scheduler.v1.EnqueueResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scheduler_v1_scheduler_proto_init() }
func file_scheduler_v1_scheduler_proto_init() {
	if File_scheduler_v1_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_v1_scheduler_proto_rawDesc), len(file_scheduler_v1_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_v1_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_v1_scheduler_proto_depIdxs,
		MessageInfos:      file_scheduler_v1_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_v1_scheduler_proto = out.File
	file_scheduler_v1_scheduler_proto_goTypes = nil
	file_scheduler_v1_scheduler_proto_depIdxs = nil
}
